postgresql:
  image: sameersbn/postgresql:9.1-1
  environment:
    - DB_USER=gitlab
    - DB_PASS=secretpassword
    - DB_NAME=gitlabhq_production
  volumes:
    - "/opt/dockerdata/gitlab/postgres/:/var/lib/postgresql"
gitlab:
  image: sameersbn/gitlab:7.7.0
  env_file:
    - env_config/gitlab
  links:
    - redis:redisio
    - postgresql:postgresql
  volumes:
    - "/opt/dockerdata/gitlab/gitlab:/home/git/data" 
redis:
  image: sameersbn/redis:latest
